version: '3.8'

services:
  fastapi:
    build: .
    image: rag-pdf:v1.0 
    ports:
      - "8000:8000"
    environment:
      - QDRANT_HOST=http://qdrant:6333
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - qdrant
      - ollama

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6663:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11435:11435"
    volumes:
      - ollama_data:/root/.ollama

  ollama-pull-model:
    image: curlimages/curl:latest
    entrypoint: [ "sh", "-c", "until curl -s http://ollama:11434/api/tags; do sleep 2; done; curl -X POST http://ollama:11434/api/pull -d '{\"name\": \"qwen2.5:0.5b\"}'" ]
    depends_on:
      - ollama

volumes:
  qdrant_data:
  ollama_data: